# Chap.4 numpy套件(numeric python)
## 為什麼需要numpy?
* numpy由c撰寫，速度快python 10~1000倍以上
* numpy儲存結果較正確，python數字儲存不正確
* numpy節省記憶體儲存空間
* numpy的向量(矩陣計算)速度快
* numpy的取值方便
# Numpy 可以產生一維、二維陣列進行向量（vector）和矩陣（matrix）運算

In [82]:
a_list=[1,2,3,4,5] #宣告 串列 a
print(a_list*3)    #顯示 串列 a 重複3次

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [83]:
#numpy套件的ndarray型態,提供element-wise的操作
import numpy  #加入 numpy 資料庫
a=numpy.array([1,2,3,4,5]) #透過 numpy 建立陣列
print(a*3)   #顯示 list a 3次

[ 3  6  9 12 15]


In [84]:
a=numpy.array([1,2,3,4,5]) #透過 numpy 建立陣列
print(type(a))  # 顯示 list a 處存類型
print(a.shape) #顯示 list a 矩陣形狀
print(a.dtype) #顯示 list a 資料型態
print(a.ndim) #顯示 list a 維度

<class 'numpy.ndarray'>
(5,)
int32
1


In [85]:
import numpy as np #加入 numpy 資料庫 到 np (讓指令簡短一些)
z=np.zeros(6)      #list z 建立長度為6 一維陣列
print(z)           #顯示 list z
print(np.empty((2,3,4)))  #np.empty(shape, dtype=float, order='C')
print(np.arange(10))       #只有結束
print(np.arange(3,8))      #起點 結束
print(np.arange(3,8,2))    #起點 結束 步長

#np.arange(start, stop, step, dtype = None)

[0. 0. 0. 0. 0. 0.]
[[[6.23042070e-307 4.67296746e-307 1.69121096e-306 3.33772792e-307]
  [1.42419938e-306 7.56603881e-307 8.45603440e-307 3.56043054e-307]
  [1.60219306e-306 6.23059726e-307 1.06811422e-306 3.56043054e-307]]

 [[1.37961641e-306 8.90071135e-308 8.01097889e-307 1.78020169e-306]
  [7.56601165e-307 1.02359984e-306 1.33510679e-306 2.22522597e-306]
  [6.23053614e-307 1.60221072e-306 1.42410974e-306 2.56761491e-312]]]
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7]
[3 5 7]


## ndarray的進階操作

In [86]:
#np.arange(start, stop, step, dtype = None)
my_array=np.arange(10)  #只有結束項 
print(my_array)         #顯示 list my_array
print(my_array[0])      #顯示 list my_array 第一項
print(my_array[0:5])    #顯示 list my_array 第一行 第六列

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


### 2維資料取值

In [87]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)]) #透過 array 建立 2*5 二微陣列
print(my_2d_array)        #顯示 陣列
print(my_2d_array[1,:])   #顯示 陣列 第2行 全部資料
print(my_2d_array[:,1])   #顯示 陣列 第1列 全部資料
print(my_2d_array[1,1])   #顯示 陣列 第1行 第1列 資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [88]:
my_array=np.arange(0,10)       #建立 1*10 陣列
print(my_array)                #顯示 1*10 陣列
print(my_array.shape)          #顯示  陣列 形狀
#-----------------------------------------------------
my_2d_array=my_array.reshape(2,5)        # 依次生成n個自然數，並且以a行b列的數組 顯示
print(my_2d_array)                       #顯示 陣列 
print((np.arange(0,100).reshape(10,10))) # 顯示 100個自然數 以10行10列的數組 排序

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### numpy的空值nan

In [89]:
b=np.array([56, 8, 19, 14, np.nan]) #宣告 串列
print(b)    #顯示 串列
#nan為 空值

[56.  8. 19. 14. nan]
